#!/usr/bin/env python3

# Copyright (c) 2019 Daniel Jakots
#
# Licensed under the MIT license. See the LICENSE file.

import os
import subprocess
import sys

REPOSITORIES_PATH = "~/git"


def usage():
    print(
        "usage: " + sys.argv[0] + " ssh://git@gitlab.com/foo/bar.git", file=sys.stderr
    )
    print("usage: " + sys.argv[0] + " https://github.com/foo/bar.git", file=sys.stderr)
    sys.exit(1)


# This gonna be dirty and full of assumptions. Try to laugh instead of cringe
def parse_url(url):
    if url[-4:] != ".git":
        print("Is '.git' missing?", file=sys.stderr)
        usage()

    if url[:3] == "ssh":
        hoster, tree, project = parse_ssh_url(url)
    elif url[:4] == "http":
        hoster, tree, project = parse_http_url(url)
    # seems to be git@example.com:foo.git
    elif ":" in url:
        url = "ssh://" + url.replace(":", "/")
        hoster, tree, project = parse_ssh_url(url)
    else:
        print("The url doesn't look like correct", file=sys.stderr)
        usage()
    return hoster, tree, project


def parse_ssh_url(url):
    _, _, loginurl, *tree, project = url[:-4].split("/")
    hoster = loginurl.split("@")[1]
    return hoster, tree, project


def parse_http_url(url):
    _, _, hoster, account, project = url[:-4].split("/")
    return hoster, tree, project


def main(url):
    hoster, tree, project = parse_url(url)
    repositories_path = os.path.expanduser(REPOSITORIES_PATH)
    path = f"{repositories_path}/{hoster}/{'/'.join(tree)}/"
    os.makedirs(path, exist_ok=True)
    subprocess.run(["git", "-C", path, "clone", url])


if __name__ == "__main__":
    if len(sys.argv) != 2:
        usage()
    url = sys.argv[1]
    main(url)
